server:
  port: 8088
spring:
  shardingsphere:
    # 配置数据源
    datasource:
      names: m0,m1,m2
      m0:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_db?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
      m1:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_1?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
      m2:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_2?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
    rules:
      sharding:
        sharding-algorithms:
          # 算法名用-连接，不要用下划线_连接
          tablesource-day-class-based:
            #自定义类分片算法 通过配置分片策略类型和算法类名，实现自定义扩展。
            # CLASS_BASED 允许向算法类内传入额外的自定义属性，传入的属性可以通过属性名为 props 的 java.util.Properties 类实例取出。
            type: CLASS_BASED
            props:
              # 如果strategy=standard 则自定义算法类需要实现org.apache.shardingsphere.sharding.api.sharding.standard.StandardShardingAlgorithm.java接口
              # 如果strategy=COMPLEX，则自定义算法类需要实现org.apache.shardingsphere.sharding.api.sharding.complex.ComplexKeysShardingAlgorithm.java接口
              # 如果strategy=HINT，则自定义算法类需要实现org.apache.shardingsphere.sharding.api.sharding.hint.HintShardingAlgorithm.java接口
              strategy: standard
              # 自定义标准分配算法
              algorithmClassName: com.cas.sharding.DayStrategyShardingAlgorithm
          tablesource-month-class-based:
            type: CLASS_BASED
            props:
              strategy: standard
              # 自定义标准分配算法
              algorithmClassName: com.cas.sharding.MonthStrategyShardingAlgorithm
          tablesource-year-class-based:
            type: CLASS_BASED
            props:
              strategy: standard
              # 自定义标准分配算法
              algorithmClassName: com.cas.sharding.YearStrategyShardingAlgorithm
          course-table:
            # inline分片算法：提供一个分片键和一个分片表达式来制定分片算法，这种方式配置简单，功能灵活，是分库分表最佳配置方式，满足大多数的分库分表场景
            type: INLINE
            props:
              # 算法表达式 $标识一个需要计算的值，"->{算法}" 通过左边这种表达式去计算
              algorithm-expression: course_$->{cid % 2 + 1}
          course-database:
            type: INLINE
            props:
              algorithm-expression: m$->{user_id % 2 + 1}
        tables:
          t_user:
            actual-data-nodes: m$->{0}.t_user
            # 主键的生成规则
            key-generator:
              column: user_id
              # 雪花算法
              type: SNOWFLAKE
            table-strategy:
              inline:
                sharding-column: user_id
                shardingAlgorithmName: t_user
          course:
            # 指定course表分布情况，配置表在哪个数据库里面，表名称都是什么
            actual-data-nodes: m$->{1..2}.course_$->{1..2}
            tableStrategy:
              standard:
                sharding-column: cid
                shardingAlgorithmName: course-table
            database-strategy:
              standard:
                sharding-column: user_id
                shardingAlgorithmName: course-database
            keyGenerateStrategy:
              column: cid
              keyGeneratorName: SNOWFLAKE
          # 虚拟表名，sql文件要用虚拟表名替代实际表名
          t_log_day:
            # 按日期分片，测试功能使用
            # 下面的分片选择为：m0.t_log_[2022|2023|2024][1|2|3|4|5|6|7|8|9|10|11|12](月份不足两位左边补0，例如1月补0为01)[1..31](天数不足两位左边补0，例如1日补0为01)
            actual-data-nodes: m$->{0}.t_log_${2022..2024}$->{(1..12).collect{t ->t.toString().padLeft(2,'0')}}$->{(1..31).collect{d -> d.toString().padLeft(2,'0')}}
            tableStrategy:
              standard:
                sharding-column: request_time
                shardingAlgorithmName: tablesource-day-class-based
          # 虚拟表名，sql文件要用虚拟表名替代实际表名
          t_log_month:
            # 按月分片，普遍使用
            actual-data-nodes: m$->{0}.t_log_${2022..2027}$->{(1..12).collect{t ->t.toString().padLeft(2,'0')}}
            tableStrategy:
              standard:
                sharding-column: request_time
                shardingAlgorithmName: tablesource-month-class-based
          # 虚拟表名，sql文件要用虚拟表名替代实际表名
          t_record_year:
            # 按月分片，普遍使用
            actual-data-nodes: m$->{0}.t_record_${2022..2027},m$->{0}.t_record
            tableStrategy:
              standard:
                sharding-column: create_date
                shardingAlgorithmName: tablesource-year-class-based
    props:
      sql-show: true

