server:
  port: 8088
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    # 配置数据源
    datasource:
      names: m1,m2,m0
      m1:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
      m2:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
      m0:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
    sharding:
      tables:
        t_user:
          # 指定course表分布情况，配置表在哪个数据库里面，表名称都是什么
          actual-data-nodes: m$->{0}.t_user
          # 指定course表里面主键cid 生成策略，SNOWFLAKE
          key-generator:
            column: user_id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: t_user
        course:
          # 指定course表分布情况，配置表在哪个数据库里面，表名称都是什么
          actual-data-nodes: m$->{1..2}.course_$->{1..2}
          # 指定course表里面主键cid 生成策略，SNOWFLAKE
          key-generator:
            column: cid
            type: SNOWFLAKE
          # 指定分片策略 约定cid值偶数添加到course_1表，如果cid是奇数添加到course_2表
          table-strategy:
            inline:
              sharding-column: cid
              algorithm-expression: course_$->{cid % 2 + 1}
          # 指定表采用如下规则
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: m$->{user_id % 2 + 1}
    # 打开日志输出
    props:
      sql:
        show: true