# org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:5.1.0 配置如下，每个版本配置都有小变动，详细看官网
server:
  port: 8088
spring:
  shardingsphere:
    # 配置数据源
    datasource:
      names: m0,m1,m2
      m0:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
      m1:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
      m2:
        # 配置数据源具体数据
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/edu_db_2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 12345678
    rules:
      sharding:
        tables:
          t_user:
            actual-data-nodes: m$->{0}.t_user
            key-generator:
              column: user_id
              type: SNOWFLAKE
            table-strategy:
              inline:
                sharding-column: user_id
                shardingAlgorithmName: t_user
          course:
            # 指定course表分布情况，配置表在哪个数据库里面，表名称都是什么
            actual-data-nodes: m$->{1..2}.course_$->{1..2}
            tableStrategy:
              standard:
                sharding-column: cid
                shardingAlgorithmName: course-table
            database-strategy:
              standard:
                sharding-column: user_id
                shardingAlgorithmName: course-database
            keyGenerateStrategy:
              column: cid
              keyGeneratorName: SNOWFLAKE
        sharding-algorithms:
          course-table:
            type: INLINE
            props:
              algorithm-expression: course_$->{cid % 2 + 1}
          course-database:
            type: INLINE
            props:
              algorithm-expression: m$->{user_id % 2 + 1}
    props:
      sql-show: true

